name: movie_watch_party
description: A futuristic movie watch party platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0
  googleapis: ^11.3.0
  googleapis_auth: ^1.3.0
  video_player: ^2.7.0
  webrtc_interface: ^0.9.0
  flutter_webrtc: ^0.9.30
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  glassmorphism: ^2.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
